---
- name: Install Nginx
  sudo: yes
  apt: name=nginx state=latest

- name: Change default nginx site
  sudo: yes
  template: src=default.template dest=/etc/nginx/sites-available/default
  notify: restart nginx
